sensor 1 law "random"
sensor 1 law "markov"
sensor 5 law "random"
sensor 5 law "markov"
sensor 6 law "random"
sensor 6 law "markov"
sensor 2 law "random"
sensor 2 law "markov"
sensor 3 law "random"
sensor 3 law "markov"
sensor 4 law "random"
sensor 4 law "markov"

runApp "toto"
